### PR TITLE
Isabel mainpage

### PR DESCRIPTION
**Pull request by isabelrsilva617**
App.js
- Router with Exams and Admin components

Exams.js
- isPatientInfo allows us to display the patient details component when true
- isExamInfor allows us to display the exam details component when true
- selectedRow allows us to set the selected exam to pass to examdetails component
- selectedPatiend allows us to set the selected patient id to pass to patientdetails component

Any changes to ExamDetails and PatientDetails were just to test that we were correctly sending props to both components

### CODE REVIEW

**Comment by Adonca2203** [comment]
This is not the final details page correct? Still waiting on @Waliyat1 and @kaibrown28 for that?
Also, you forgot to merge the new main, will do that for you.

**Comment by isabelrsilva617** [comment]
> This is not the final details page correct? Still waiting on @Waliyat1 and @kaibrown28 for that?
> Also, you forgot to merge the new main, will do that for you.

@Adonca2203 Correct

**Review by Adonca2203 — APPROVED** [review]
Looks great!
Merged

**Comment by kaibrown28** [comment]
I'm checking in with @Waliyat1<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWaliyat1&data=05%7C01%7C%7C5b65dc2ddeb340e8884208db21ae2cee%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638140804187156894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5xyFHZhHlJPtDke2UxqwuPpYPxJPUfrvA3gi5L20sOA%3D&reserved=0>  as I'm a little stuck - just missing three pieces of info from the exam details page.
________________________________

**Pull request merged**
